### ISSUE TITLE
"Signature Expired" Error Message When Using AWS STS Command

### ISSUE THREAD

**Issue by Scoggin** [devsecops/bootcamp#101]
When using STS to assume the control account control I experienced the following error: 

`A client error (SignatureDoesNotMatch) occurred when calling the AssumeRole operation: Signature expired: 20160609T184512Z is now earlier than 20160610T013008Z (20160610T014508Z - 15 min.)
`

This is resulting from having the local time discrepant by 15 or more minutes.

**Comment by Scoggin** [comment]
This is resolved by syncing your local system time to that of the server

**Comment by pbnj** [comment]
@Scoggin Thank you for tracking this issue.
