### ISSUE TITLE
AWS STS "Invalid IPv6 URL" error (week 3 labs)

### ISSUE THREAD

**Issue by ggrpmnn** [devsecops/bootcamp#123]
I encountered this error during the week 3 labs. This issue shows when trying to run an STS command (aws sts ...) and simply outputs "Invalid IPv6 URL". I'm not sure what the root cause of the error is, but I fixed it by doing the following.

1) removing the profile from my .aws/credentials file
2) deleting the key I was assigned via the AWS Console (in a broswer)
3) getting a new key and setting up the profile as normal using aws configure

Resetting the keys enabled me to properly use STS and other AWS commands.

**Comment by pbnj** [comment]
Thank you for sharing! I know a few other Windows users were running into the same error.
