### ISSUE TITLE
create a devsecops box

### ISSUE THREAD

**Issue by SxMShaDoW** [devsecops/bootcamp#167]
We shouldn't be rebuilding and running aws, ruby, etc everytime you vagrant up. 
- One option is move it to a chef cookbook first and then use packer (https://www.packer.io/intro/getting-started/build-image.html) to create a ami, vbox, vmfusion, or etc.
- Another option is to use`vagrant package`(https://www.vagrantup.com/docs/cli/package.html)
- Once the image is created store it in the public vagrant catalog

**Comment by godinezj** [comment]
This is a great project for week 8 & 9.

```
The Capstone Project: Now that we've accomplished two rounds of DevSecOps and improved our skills significantly, it's time to build something that helps solve a problem.
```

**Comment by SxMShaDoW** [comment]
Sure. I can do this for the project (and if you want to help @godinezj i'd be down)

**Comment by godinezj** [comment]
@SxMShaDoW looks like @johandry is already working on this: https://github.com/johandry/DevSecOpsVirtualEnv I suggest you guys team up on this.

**Comment by slietz** [comment]
Did this get done?

**Comment by godinezj** [comment]
It did.
