### ISSUE TITLE
Lab 3 content is not available

### ISSUE THREAD

**Issue by pil123** [devsecops/bootcamp#184]
For Lab 3, 'git clone git@github.com:devsecops/bootcamp.git' returns the following error:

$ git clone git@github.com:devsecops/bootcamp.git                                                                                          Cloning into 'bootcamp'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.                                    git@github.com: Permission denied (publickey).                                                                                             fatal: Could not read from remote repository.
--

**Comment by slietz** [comment]
This is a github warning and not an error for the repo.
